version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=???
      - PRIVATE_KEY=???
      - CONNECT=Czech_Republic
      - NETWORK=192.168.1.0/24
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000     
      - PGID=1000
    volumes:
      - /docker_config/qbittorrent:/config
      - /pool0/Heh/Torrents:/downloads #optional
    depends_on:
      - vpn

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=??? #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /docker_config/plex:/config
      - /pool0/Heh/Series:/tv
      - /pool0/Heh/Movies:/movies
    runtime: nvidia
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_config/radarr:/config
      - /pool0/Heh/Movies:/movies
      - /pool0/Heh/Torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_config/sonarr:/config
      - /pool0/Heh/Series:/tv
      - /pool0/Heh/Torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
    volumes:
      - /docker_config/jackett:/config
      - /pool0/Heh/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  booksonic-air:
    image: lscr.io/linuxserver/booksonic-air:latest
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_config/booksonic_air:/config
      - /pool0/Heh/audiobooks:/audiobooks
      - /pool0/Heh/podcasts:/podcasts
      - /pool0/Heh/othermedia:/othermedia
    ports:
      - 4040:4040
    restart: unless-stopped
  readarr-audiobooks:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_config/readarr_audiobooks:/config
      - /pool0/Heh/audiobooks:/audiobooks
      - /pool0/Heh/Torrents:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
